opam-version: "2.0"
authors: "François Pottier <francois.pottier@inria.fr>"
maintainer: "François Pottier <francois.pottier@inria.fr>"
homepage: "https://gitlab.inria.fr/fpottier/array"
bug-reports: "https://gitlab.inria.fr/fpottier/array/issues"
dev-repo: "git+https://gitlab.inria.fr/fpottier/array/"
version: "dev"
synopsis: "More array support for Rocq"
tags: [
  "logpath:array"
]

depends: [
  "rocq-core" { (>= "9.0") }
  "rocq-stdlib"
  "rocq-stdpp"
]
